apiVersion: iam.services.k8s.aws/v1alpha1
kind: Policy
metadata:
  name: s3-access-policy
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  name: s3-access-policy
  policyDocument:
    version: "2012-10-17"
    statement:
      - effect: Allow
        action:
          - "s3:*"
        resource:
          - "arn:aws:s3:::my-app-bucket"
          - "arn:aws:s3:::my-app-bucket/*"

