
apiVersion: iam.services.k8s.aws/v1alpha1
kind: Role
metadata:
  name: s3-access-role
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  name: s3-access-role
  assumeRolePolicyDocument: |
    {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Effect": "Allow",
          "Principal": {
            "Service": "ec2.amazonaws.com"
          },
          "Action": "sts:AssumeRole"
        }
      ]
    }
  policies:
    - reference:
        name: s3-access-policy