apiVersion: iam.services.k8s.aws/v1alpha1
kind: Policy
metadata:
  name: s3-access-policy
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  policyName: s3-access-policy
  policyDocument: |
    {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Effect": "Allow",
          "Action": "s3:*",
          "Resource": [
            "arn:aws:s3:::{{ .Values.s3.bucketName }}",
            "arn:aws:s3:::{{ .Values.s3.bucketName }}/*"
          ]
        }
      ]
    }

