apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: s3-role-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/7navyasa/crossplane-demo.git'
    targetRevision: ack-helm
    path: ack-helm
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ack-helm-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  # annotations:
  #   argocd.argoproj.io/sync-wave: "1"  # Deploy firsts