apiVersion: v2
name: s3-access-app
description: A Helm chart to deploy an S3 bucket, IAM policy, and IAM role using ACK and Argo CD.
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: app
    version: 0.1.0
    repository: "file://./charts/app"
  - name: sa
    version: 0.1.0
    repository: "file://./charts/sa"